language: node_js

node_js:
  - "12"

dist: trusty

services:
  - docker

if: type = pull_request OR branch = main OR tag IS present

addons:
  chrome: stable
  apt:
    packages:
      - libgconf-2-4

cache:
  directories:
    - ~/.npm
    - ~/.cache

script:
  - npm run lint
  - npm run cy:ci

before_deploy:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - docker build -t ci-ui .
  - docker images
  - docker tag ci-ui $DOCKER_USERNAME/ci-ui
  - docker push $DOCKER_USERNAME/ci-ui

deploy:
  - provider: script
    skip_cleanup: true
    script: echo "DONE!"
    on:
      tags: true
