language: node_js

node_js:
  - "12"

dist: trusty

services:
  - docker

if: type = pull_request OR branch = main OR tag IS present

addons:
  chrome: stable
  apt:
    packages:
      - libgconf-2-4

cache:
  directories:
    - ~/.npm
    - ~/.cache

script:
  - npm run lint
  - npm run cy:ci

deploy:
  - provider: script
    skip_cleanup: true
    script: bash docker_push.sh
    on:
      branch: main
